/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Clear handheld albedo accumulation

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout(local_size_x = 256, local_size_y = 1) in;
const ivec3 workGroups = ivec3(1, 1, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#define HANDHELD_ALBEDO_ACCESS restrict
#include "/lib/lighting/HandheldAlbedo.glsl"

//======// Main //================================================================================//
void main() {
	uint index = gl_LocalInvocationID.x;
	for (; index < HANDHELD_ALBEDO_BUCKET_COUNT; index += gl_WorkGroupSize.x) {
		handheldAlbedo.buckets[index] = uvec4(0u);
	}

	if (gl_LocalInvocationID.x == 0u && historyReset) {
		handheldAlbedo.average = vec4(0.0);
		handheldAlbedo.state = uvec4(0u);
	}
}
